### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Goldstein777** [Ketcap/Convrs.dev#7]
**Is your feature request related to a problem? Please describe.**
Bright screen hurts.

**Describe the solution you'd like**
Dark Theme.

**Describe alternatives you've considered**
Switch between white and dark theme.

**Additional context**
None.

**Comment by Ketcap** [comment]
[@feat/ui-update](https://github.com/Ketcap/Talk-to-AI/tree/feat/ui-update) has kicked off here.

**Comment by Ketcap** [comment]
solved with https://github.com/Ketcap/Convrs.dev/commit/4e9e5e0a410a3563498f830fe11f14aa205c7e10
